name: Build Binaries Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build for x86_64 Mac 
        run: rustup target add x86_64-apple-darwin && cargo build --release --target x86_64-apple-darwin

      - name: Archive x86_64 binary for linux based
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-linux-based
          path: target/release/heybud

      - name: Build for x86_64 windows
        run: rustup target add x86_64-pc-windows-msvc cargo build --release --target x86_64-pc-windows-msvc

      - name: Archive x86_64 binary for windows based
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-windows
          path: target/release/heybud.exe

